AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 para analise de xadrez com Stockfish + Jupyter

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: KeyPair para acesso SSH

  InstanceType:
    Type: String
    Default: c7a.4xlarge
    AllowedValues:
      - c7a.2xlarge
      - c7a.4xlarge
      - c6i.4xlarge
    Description: Tipo da instância

Resources:
  ChessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acesso SSH e Jupyter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8888
          ToPort: 8888
          CidrIp: 0.0.0.0/0

  ChessInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref ChessSecurityGroup
      ImageId: ami-0c7217cdde317cfec # Ubuntu 22.04 LTS (ajuste por região)
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
            VolumeType: gp3
      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -e

          apt update
          apt upgrade -y

          # Dependencias
          apt install -y \
            python3 \
            python3-pip \
            python3-venv \
            stockfish \
            git \
            htop

          # Clone do repositorio
          sudo -u ubuntu git clone https://github.com/arturbernardo/chess_statistics.git \
          /home/ubuntu/chess_statistics

          # Parallel 
          sudo apt install parallel

          #pgn manipulator
          sudo apt update
          sudo apt install pgn-extract

          # Jupyter
          pip3 install --upgrade pip
          pip3 install jupyterlab notebook

          # Python Chess
          pip3 install python-chess

          # Usuario ubuntu
          mkdir -p /home/ubuntu/jupyter
          chown -R ubuntu:ubuntu /home/ubuntu/jupyter

          # Config Jupyter
          sudo -u ubuntu jupyter lab --generate-config
          CONFIG=/home/ubuntu/.jupyter/jupyter_lab_config.py

          echo "c.ServerApp.ip = '0.0.0.0'" >> $CONFIG
          echo "c.ServerApp.open_browser = False" >> $CONFIG
          echo "c.ServerApp.port = 8888" >> $CONFIG
          echo "c.ServerApp.allow_root = True" >> $CONFIG

          # Service
          cat <<EOF > /etc/systemd/system/jupyter.service
          [Unit]
          Description=Jupyter Lab
          After=network.target

          [Service]
          Type=simple
          User=ubuntu
          ExecStart=/usr/local/bin/jupyter lab --notebook-dir=/home/ubuntu/jupyter
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF

          systemctl daemon-reload
          systemctl enable jupyter
          systemctl start jupyter

Outputs:
  PublicIP:
    Description: IP publico da EC2
    Value: !GetAtt ChessInstance.PublicIp
