AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 para analise de xadrez com Stockfish

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Type: String
    Default: c7a.4xlarge
    AllowedValues:
      - c7a.2xlarge
      - c7a.4xlarge
      - c6i.4xlarge

  HttpPort:
    Type: Number
    Default: 8000

  GameUser:
    Type: String
    Default: ArturBK

  GameType:
    Type: String
    Default: blitz

  Start:
    Type: Number
    Description: Epoch millis (obrigatório)

  End:
    Type: Number
    Description: Epoch millis (obrigatório)

Resources:
  ChessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acesso SSH e HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: !Ref HttpPort
          ToPort: !Ref HttpPort
          CidrIp: 0.0.0.0/0

  ChessInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref ChessSecurityGroup
      ImageId: ami-0c7217cdde317cfec
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
            VolumeType: gp3
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -ex

          apt-get update
          apt-get upgrade -y

          apt-get install -y \
            python3 \
            python3-pip \
            stockfish \
            git \
            curl \
            htop \
            parallel \
            pgn-extract

          pip3 install chess pandas matplotlib tqdm

          sudo -u ubuntu git clone https://github.com/arturbernardo/chess_statistics.git \
            /home/ubuntu/chess_statistics

          chown -R ubuntu:ubuntu /home/ubuntu/chess_statistics

          # ================= HTTP SERVER =================
          cat <<EOF >/etc/systemd/system/http8000.service
          [Unit]
          Description=Python HTTP Server
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/chess_statistics/server
          ExecStart=/usr/bin/python3 -m http.server ${HttpPort}
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF

          # ================= DOWNLOAD SERVICE =================
          cat <<EOF >/etc/systemd/system/lichess-download.service
          [Unit]
          Description=Download games from Lichess
          After=network.target

          [Service]
          Type=oneshot
          User=ubuntu
          Environment=LICHESS_USER=${GameUser}
          Environment=PERF_TYPE=${GameType}
          Environment=SINCE=${Start}
          Environment=UNTIL=${End}

          ExecStart=/bin/bash -c '\
            URL="https://lichess.org/api/games/user/$$LICHESS_USER?rated=true&tags=true&clocks=false&evals=false&opening=false&literate=false&since=$$SINCE&until=$$UNTIL&perfType=$$PERF_TYPE" && \
            curl -L -H "Accept: application/x-chess-pgn" "$$URL" -o /home/ubuntu/games.pgn \
          '
          EOF

          # ================= ANALYSIS SERVICE =================
          cat <<EOF >/etc/systemd/system/chess-analysis.service
          [Unit]
          Description=Chess analysis
          After=lichess-download.service
          Requires=lichess-download.service

          [Service]
          Type=oneshot
          User=ubuntu
          WorkingDirectory=/home/ubuntu/chess_statistics

          ExecStart=/bin/bash -c '\
            python3 pgn_to_fen.py /home/ubuntu/games.pgn \
              | python3 eval.py \
              | { read -r header; echo "$header"; sort -t, -k1,1n -k2,2n; } \
              | python3 cpl.py \
              > analysis.csv && \
            python3 plot_cpl.py \
          '
          EOF

          systemctl daemon-reexec
          systemctl daemon-reload

          systemctl enable http8000
          systemctl enable lichess-download
          systemctl enable chess-analysis

          systemctl start http8000
          systemctl start lichess-download
          systemctl start chess-analysis

Outputs:
  PublicIP:
    Description: IP publico da EC2
    Value: !GetAtt ChessInstance.PublicIp
