AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 para analise de xadrez com Stockfish + Jupyter

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: KeyPair para acesso SSH

  InstanceType:
    Type: String
    Default: c7a.4xlarge
    AllowedValues:
      - c7a.2xlarge
      - c7a.4xlarge
      - c6i.4xlarge
    Description: Tipo da instância

Resources:
  ChessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acesso SSH e Jupyter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8888
          ToPort: 8888
          CidrIp: 0.0.0.0/0

  ChessInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref ChessSecurityGroup
      ImageId: ami-0c7217cdde317cfec # Ubuntu 22.04 LTS (ajuste por região)
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
            VolumeType: gp3
      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -eux

          apt-get update
          apt-get upgrade -y

          # Repos
          apt-get install -y software-properties-common
          add-apt-repository universe
          apt-get update

          # Dependências (NUNCA sem -y)
          apt-get install -y \
            python3 \
            python3-pip \
            python3-venv \
            stockfish \
            git \
            htop \
            parallel \
            pgn-extract

          # Repo
          sudo -u ubuntu git clone https://github.com/arturbernardo/chess_statistics.git \
            /home/ubuntu/chess_statistics

          # chmod project
          chmod -Rf 777 /home/ubuntu/chess_statistics

          #Python chess 
          pip3 install chess

          # Ambiente Python do ubuntu
          sudo -u ubuntu python3 -m venv /home/ubuntu/venv
          sudo -u ubuntu /home/ubuntu/venv/bin/pip install --upgrade pip
          sudo -u ubuntu /home/ubuntu/venv/bin/pip install \
            jupyterlab notebook python-chess

          # Jupyter dir
          mkdir -p /home/ubuntu/jupyter
          chown -R ubuntu:ubuntu /home/ubuntu/jupyter

          # Config Jupyter
          sudo -u ubuntu /home/ubuntu/venv/bin/jupyter lab --generate-config
          CONFIG=/home/ubuntu/.jupyter/jupyter_lab_config.py

          cat >> $CONFIG <<EOF
          c.ServerApp.ip = '0.0.0.0'
          c.ServerApp.open_browser = False
          c.ServerApp.port = 8888
          c.ServerApp.allow_root = False
          EOF

          # Service
          cat <<EOF > /etc/systemd/system/jupyter.service
          [Unit]
          Description=Jupyter Lab
          After=network.target

          [Service]
          Type=simple
          User=ubuntu
          ExecStart=/home/ubuntu/venv/bin/jupyter lab --notebook-dir=/home/ubuntu/jupyter
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF

          systemctl daemon-reload
          systemctl enable jupyter
          systemctl start jupyter


Outputs:
  PublicIP:
    Description: IP publico da EC2
    Value: !GetAtt ChessInstance.PublicIp
