AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 para analise de xadrez com Stockfish

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Type: String
    Default: c7a.4xlarge
    AllowedValues:
      - c7a.2xlarge
      - c7a.4xlarge
      - c6i.4xlarge

  HttpPort:
    Type: Number
    Default: 8000

  GameUser:
    Type: String
    Default: ArturBK

  GameUserLower:
    Type: String
    Default: arturbk

  SizeLimit:
    Type: Number
    Default: 100

  GameType:
    Type: String
    Default: blitz

  Start:
    Type: Number
    Description: Epoch millis (obrigatório)

  End:
    Type: Number
    Description: Epoch millis (obrigatório)

Resources:
  ChessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acesso SSH e HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: !Ref HttpPort
          ToPort: !Ref HttpPort
          CidrIp: 0.0.0.0/0

  ChessAnalysisBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub chess-analysis-${GameUserLower}-${AWS::AccountId}

  ChessInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3UploadAnalysis
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub arn:aws:s3:::chess-analysis-${GameUserLower}-${AWS::AccountId}/*

  ChessInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ChessInstanceRole

  ChessInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref ChessInstanceProfile
      SecurityGroups:
        - !Ref ChessSecurityGroup
      ImageId: ami-0c7217cdde317cfec
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
            VolumeType: gp3

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          apt-get update
          apt-get upgrade -y

          apt-get install -y \
            python3 \
            python3-pip \
            stockfish \
            git \
            curl \
            htop \
            parallel \
            pgn-extract \
            awscli

          pip3 install chess pandas matplotlib tqdm

          git clone https://github.com/arturbernardo/chess_statistics.git \
            /home/ubuntu/chess_statistics

          chown -R ubuntu:ubuntu /home/ubuntu/chess_statistics

          # ================= DOWNLOAD SCRIPT =================
          cat >/usr/local/bin/lichess-download.sh <<'EOF'
          #!/usr/bin/env bash
          set -e

          URL="https://lichess.org/api/games/user/${GameUser}?rated=true&tags=true&clocks=false&evals=false&opening=false&literate=false&max=${SizeLimit}&since=${Start}&until=${End}&perfType=${GameType}"

          echo "Downloading: $URL"

          curl -fL -H "Accept: application/x-chess-pgn" \
            "$URL" \
            -o /home/ubuntu/games.pgn
          EOF

          chmod +x /usr/local/bin/lichess-download.sh

          # ================= HTTP SERVER =================
          cat >/etc/systemd/system/http8000.service <<EOF
          [Unit]
          Description=Python HTTP Server
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/chess_statistics/server
          ExecStart=/usr/bin/python3 -m http.server ${HttpPort}
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF

          # ================= DOWNLOAD SERVICE =================
          cat >/etc/systemd/system/lichess-download.service <<EOF
          [Unit]
          Description=Download games from Lichess
          After=network-online.target
          Wants=network-online.target

          [Service]
          Type=oneshot
          User=ubuntu
          ExecStart=/bin/bash -c 'chown ubuntu:ubuntu /home/ubuntu/games.pgn || true; exec /usr/local/bin/lichess-download.sh'

          [Install]
          WantedBy=multi-user.target
          EOF

          # ================= ANALYSIS SCRIPT =================
          cat >/usr/local/bin/run-chess-analysis.sh <<'EOF'
          #!/usr/bin/env bash
          set -euo pipefail

          BASE=/home/ubuntu/chess_statistics
          INPUT=/home/ubuntu/games.pgn

          STEP1=$BASE/01_pgn.csv
          STEP2=$BASE/02_eval.csv
          STEP3=$BASE/03_sorted.csv
          OUT=$BASE/analysis.csv

          /usr/bin/python3 $BASE/pgn_to_fen.py "$INPUT" > "$STEP1"

          /usr/bin/python3 $BASE/eval.py < "$STEP1" > "$STEP2"

          {
            head -n 1 "$STEP2"
            tail -n +2 "$STEP2" | sort -t, -k1,1n -k2,2n
          } > "$STEP3"

          /usr/bin/python3 $BASE/cpl.py < "$STEP3" > "$OUT"

          /usr/bin/python3 $BASE/plot_cpl.py "$OUT"

          BUCKET="chess-analysis-${GameUserLower}-${AWS::AccountId}"

          aws s3 cp "$OUT" "s3://$BUCKET/analysis.csv"
          EOF

          chmod +x /usr/local/bin/run-chess-analysis.sh
          chown ubuntu:ubuntu /usr/local/bin/run-chess-analysis.sh

          # ================= ANALYSIS SERVICE =================
          cat >/etc/systemd/system/chess-analysis.service <<EOF
          [Unit]
          Description=Chess analysis
          After=lichess-download.service
          Requires=lichess-download.service
          ConditionPathExists=/home/ubuntu/games.pgn

          [Service]
          Type=oneshot
          User=ubuntu
          WorkingDirectory=/home/ubuntu/chess_statistics
          Environment=LANG=C
          Environment=LC_ALL=C
          ExecStart=/usr/local/bin/run-chess-analysis.sh

          [Install]
          WantedBy=multi-user.target
          EOF


          systemctl daemon-reload
          systemctl enable http8000 lichess-download chess-analysis
          systemctl start http8000
          systemctl start lichess-download
          systemctl start chess-analysis

Outputs:
  PublicIP:
    Description: IP publico da EC2
    Value: !GetAtt ChessInstance.PublicIp
